### PR TITLE
Feature/microsoft graph

### PR DESCRIPTION
**Pull request by AlexTeusz**
Created a Microsoft Graph Custom Module to provide some basic Graph functions, such as getting user details or scheduling a meeting.

For more information take a look in the Azure Board.

### CODE REVIEW

**Comment by Cesarcs7** [comment]
The step 6 from **Use the Azure CM for login to Microsoft** says the following:

Go back to your project and use the **Start Authentication With ADAL** node. 7. You will find it under the path Create Node/Modules/azure/ in the node creation menu.

I uploaded the Azure CM from the cognigy documentation, but when i wanted to create that Node, the option was not there in the Node creation menu
Screenshot from 2019-08-26 14-40-33


am i uploading the correct Azure CM? im using the one in the documentation


Screenshot from 2019-08-26 14-42-31

**Comment by AlexTeusz** [comment]
PR 5419

**Comment by strafbier** [comment]
It seems i do not have access to getEventsFromCalendar for my own user.
Might be a configuration in azure, might be an error in the code.

**Comment by strafbier** [comment]
Same goes for sendMail

**Comment by AlexTeusz** [comment]
It has to be a configuration in Azure. Please use my credentials to test it.

**Pull request merged**
