### PR TITLE
Feature/zipcode city

### PR DESCRIPTION
**Pull request by kwinto**

### CODE REVIEW

**Comment by AlexTeusz** [comment]
@kwinto is this still in development? I see that you forked the repository. I think this PR here is not necessary, is it?

**Comment by kwinto** [comment]
I am not sure. It is finished, tested and can be used. But it is limited to the german post codes.

**Comment by AlexTeusz** [comment]
@kwinto if it is finished and working, then please merge it into the master and delete this PR here :) thank you

**Comment by kwinto** [comment]
It is not reviewed yet, @pedily can you check this?

**Pull request merged**
