### PR TITLE
added createJiraTicket node

### PR DESCRIPTION
**Pull request by AlexTeusz**
I implemented the **createJiraTicket** node to create a new ticket in your jira project. 

To test this PR, you need the following: 
- Cognigy Secret (ask me for test credentials)
- The **Jira** Custom Module

Create a new project and create a new flow. Create a Cognigy Secret.
Create the Node **createJiraTicket** from the **Jira** Custom Module. 

The following arguments have to be defined in the Node: 
- summary (e.g. beer is empty)
- projectId (in this case "CI" (ci)
- epicname (Keyword for this issue, e.g. beer)
- description (text)
- assignee (isn't required)
- store

The response will be the new jira ticket.

The ticket is now in the JIRA instance. Ask me for access.

### CODE REVIEW

**Comment by robinschuster** [comment]
the convention says that we should call the field `contextStore`, not `store`

**Comment by robinschuster** [comment]
i cannot create a ticket as described, i get `null` written into the context instead of a response (might be a 400 response)

**Comment by AlexTeusz** [comment]
@robinschuster I change the field `store` to `contextStore`

**Comment by AlexTeusz** [comment]
@robinschuster I added a better error message for false credentials.

**Pull request merged**
