### PR TITLE
working weather module

### PR DESCRIPTION
**Pull request by AlexTeusz**
Implemented a Custom Module for accessing the weather data of a chosen city.

See Azure Board PR: 5428

### CODE REVIEW

**Comment by mastasky** [comment]
This module doesn't work as described. Possibly the temperature function in the underlying npm changes?

```
/mnt/c/Users/phelt/Repos/CustomModules/modules/open-weather-map/node_modules/openweather-apis/index.js:149
      return callback(err,jsonObj.main.temp);
                                       ^

TypeError: Cannot read property 'temp' of undefined
    at /mnt/c/Users/phelt/Repos/CustomModules/modules/open-weather-map/node_modules/openweather-apis/index.js:149:40
    at IncomingMessage.<anonymous> (/mnt/c/Users/phelt/Repos/CustomModules/modules/open-weather-map/node_modules/openweather-apis/index.js:237:18)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

@AlexTeusz  - Please review.

**Comment by AlexTeusz** [comment]
@mastasky I'm currently testing the module and everything is working for me. I pulled it again, installed all services again and built it again. Then I uploaded it again and tested it. Everything is working.

Env: Internal
Project: WeatherAPIDemo

// Alex

**Comment by AlexTeusz** [comment]
@pedily bitte an dmitrii weiterleiten. hat @mayrbenjamin92 gesagt.

**Comment by AlexTeusz** [comment]
@kwinto did @mayrbenjamin92 forwarded this pull request to you? see the comment above.

**Comment by mastasky** [comment]
The underlying module was fixed!

**Pull request merged**
